apiVersion: v1
kind: PersistentVolume
metadata:
  name: couchbase-data2
  labels:
    type: cb
spec:
 storageClassName: slow
 capacity:
   storage: 2Gi
 accessModes:
   - ReadWriteOnce
 hostPath: 
  path: /home/cb2
